# Generated by Django 5.1.2 on 2024-10-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages='Укажите действующий email на него придет сообщение с ссылкой для подтверждения', max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
