# Generated by Django 5.1.2 on 2024-10-27 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('platinum', 'Платина')], error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите материал')),
                ('weight', models.FloatField(error_messages='Укажите вес изделия в граммах', verbose_name='вес в граммах')),
                ('result', models.FloatField(blank=True, default=0, null=True, verbose_name='результат')),
                ('owner', models.ForeignKey(blank=True, help_text='укажите владельца', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
