# Generated by Django 5.1.2 on 2024-10-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('platinum', 'Платина')], error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите материал')),
                ('weight', models.FloatField(error_messages='Укажите вес изделия в граммах', verbose_name='вес в граммах')),
                ('sample', models.CharField(choices=[('999', '999'), ('958', '958'), ('900/916', '900/916'), ('850', '850'), ('750', '750'), ('583/585', '583/585'), ('500/555', '500/555'), ('375', '375')], error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите пробу')),
                ('result', models.FloatField(blank=True, default=0, null=True, verbose_name='результат')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
    ]
