# Generated by Django 5.1.2 on 2024-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='material',
            field=models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('platinum', 'Платина')], default='Золото', error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите материал'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sample',
            field=models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('platinum', 'Платина')], error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите пробу'),
        ),
    ]
