# Generated by Django 5.1.2 on 2024-10-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_sale_material_alter_sale_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sample',
            field=models.CharField(choices=[('999', '999'), ('958', '958'), ('900/916', '900/916'), ('850', '850'), ('750', '750'), ('583/585', '583/585'), ('500/555', '500/555'), ('375', '375')], error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите пробу'),
        ),
    ]
