# Generated by Django 5.1.2 on 2024-10-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_sale_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sample',
        ),
        migrations.AddField(
            model_name='sale',
            name='sample_gold',
            field=models.CharField(choices=[('none', 'неизвестно'), ('999', '999'), ('958', '958'), ('900/916', '900/916'), ('850', '850'), ('750', '750'), ('583/585', '583/585'), ('500/555', '500/555'), ('375', '375')], default='неизвестно', error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите пробу золота'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sample_platinum',
            field=models.CharField(choices=[('none', 'неизвестно'), ('999', '999'), ('950', '950'), ('900', '900'), ('850', '850'), ('800', '800')], default='неизвестно', error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите пробу платины'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sample_silver',
            field=models.CharField(choices=[('none', 'неизвестно'), ('999', '999'), ('925', '925'), ('900', '900'), ('875', '875'), ('800', '800'), ('750', '750'), ('600', '600')], default='неизвестно', error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите пробу серебра'),
        ),
    ]
