# Generated by Django 5.1.2 on 2024-11-01 13:28

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_sale_sample_sale_sample_gold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Making',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('platinum', 'Платина')], default='Золото', error_messages='Поле обязательно для заполнения', max_length=150, verbose_name='выберите материал')),
                ('weight', models.FloatField(error_messages='Укажите вес изделия в граммах', verbose_name='вес в граммах')),
                ('description', models.TextField(max_length=300, verbose_name='Опишите изделие / Прокомментируйте заказ')),
                ('image_one', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=77, scale=None, size=[600, 600], upload_to='users/making/', verbose_name='картинка с похожим изделием')),
                ('image_two', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=77, scale=None, size=[600, 600], upload_to='users/making/', verbose_name='картинка с похожим изделием')),
                ('result', models.FloatField(blank=True, default=0, null=True, verbose_name='результат')),
                ('owner', models.ForeignKey(blank=True, help_text='укажите владельца', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
        ),
    ]
